name: GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-profile-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: michycipher
          BRANCH_NAME: main
          UTC_OFFSET: 1
          AUTO_PUSH: true
          THEME: radical

  github-rank-card:
    runs-on: ubuntu-latest
    needs: github-profile-summary

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create profile folder
        run: mkdir -p profile

      - name: Generate C+ GitHub rank card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
          username: michycipher
          path: profile/github-rank.svg
          query: >-
            show_icons=true
            &include_all_commits=true
            &show=prs_merged,reviews
            &theme=radical
            &hide_border=false
            &rank_icon=default
            &custom_title=Michelle%20Utomi%20GitHub%20Stats

      - name: Commit generated rank card
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/github-rank.svg
          git commit -m "chore: update GitHub rank stats" || exit 0
          git push

  github-streak:
    runs-on: ubuntu-latest
    needs: github-rank-card

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create profile folder
        run: mkdir -p profile

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          token: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
          path: profile/streak.svg
          options: user=michycipher&theme=radical&hide_border=false

      - name: Commit generated streak card
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "chore: update GitHub streak stats" || exit 0
          git push
